---
title: A Conversation Across the Centuries
subtitle: How My Grand-Aunt Esther’s Stories Brought Our Relative's Andersonville Ordeal to Life
author: Brent Benson
categories: ["ancestry", "history"]
---

While reading my Grandaunt Esther Stockwell's memoir *Asia's Call* I
realized that Esther, my Grandmother Katherine Benson's sister and
someone I met on several occasions, had visited with her Grandfather
Joseph Daniel Beck. Joseph Beck fought for the North with the Illinois
14th Regiment in the Civil War and was imprisoned in the infamous
Andersonville Confederate Prison in South Carolina.

While it seemed improbably to me, I knew someone who knew one of my
Civil War veteran relatives.

Esther wrote in the chapter *Nebraska Days*:

> During the summers, Frances and I visited...Uncle Frank Beck and
> Aunt Mary, who lived on a farm between Bruning and Carleton,
> Nebraska...Grandpa Beck also made his home with Uncle Frank. He had
> lived there ever since his second wife died. He couldn't hear very
> well, but he could see. He read the papers and talked to us, yet he
> never went to church. He also chewed tobacco. I hated the habit, but
> liked his stories. He had fought in the South during the Civil War
> and often told us about those terrible years. The fighting was
> unbelievably fierce and many of his comrades were killed. He,
> himself, was captured and held in the infamous, filthy Andersonville
> Prison. The living conditions were unspeakable. The rotten potatoes
> they had to eat were infested with worms. He miraculously survived,
> and after the war ended, he made his slow way back home. When he
> regained his health, he resumed work in his blacksmith shop.


