project:
  type: website
  output-dir: docs

website:
  title: "Brent Benson"
  site-url: https://brentwbenson.org
  google-analytics: "G-VGEHLT4S8G"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bwbensonjr/bwb-blog
      - icon: threads
        href: https://threads.net/bwbensonjr
      - icon: linkedin
        href: https://www.linkedin.com/in/bwbenson/
        
format:
  html:
    theme: litera
    css: styles.css



